Repository mydumper/mydumper, pull requests merged in 2021-09, with the labels that each got.

#399 Table and database names changed to fix several issues
  mydumper.c
  mydumper.h
  myloader.c
  myloader.h
Labels: Fix

#69 Dump procedures and functions using case sensitive database name
  mydumper.c
Labels: bug, enhancement

#376 improve estimated_step
  mydumper.c
Labels: enhancement

#401 [ Fix ] on table name segfault and add free functions
  mydumper.c
  mydumper.h
Labels: Refactoring, Fix

#406 [Fix] missing strdup on database job creation
  mydumper.c
Labels: Fix

#410 Bad comparison in current_database
  myloader.c
Labels: Fix
