Repository mydumper/mydumper, pull requests merged in 2021-08, with the labels that each got.

#386 Tables without indexes can cause segfault
  mydumper.c
Labels: bug

#370 Adding config file functionality
  common.c
  common.h
  mydumper.c
  myloader.c
Labels: enhancement

#352 Adding sync mechanism and constraint split
  myloader.c
  myloader.h
Labels: enhancement

#387 Fix on Debian version
  common.c
Labels: Fix

#390 [ fix ] The count was incorrect
  myloader.c
Labels: Fix

#392 Avoid logging SQL data on error
  myloader.c
Labels: Fix

#394 Reading file list only one time
  myloader.c
  myloader.h
Labels: Refactoring

#397 [ Fix ] When no index, alter_table_statement must be NULL
  myloader.c
Labels: Fix

#398 Adding the set session execution
  myloader.c
Labels: Fix
