Repository mydumper/mydumper, pull requests merged in 2021-06, with the labels that each got.

#359 Adding libatomic1 dependency reference
  README.md
Labels: Documentation

#355 Fix checksum compression
  mydumper.c
  myloader.c
Labels: Fix

#191 Dump strings using single quote instead of double quotes
  mydumper.c
Labels: enhancement

#213 Fix the create database section when creating with --source-db enabled
  myloader.c
Labels: bug, enhancement

#347 Adding --where support
  mydumper.c
Labels: enhancement

#353 Adding metadata file per table that contains the amount of rows
  mydumper.c
  mydumper.h
Labels: enhancement

#332 Abstract function for io
  common.h
  mydumper.c
  mydumper.h
Labels: Refactoring

#362 Fixing master after last merge
  mydumper.c
Labels: Fix

#366 [Fix] New database was not being created
  myloader.c
Labels: Fix

#367 [Refactoring] Using m_close
  mydumper.c
Labels: Refactoring
