Repository mydumper/mydumper, pull requests merged in 2021-03, with the labels that each got.

#295 Allow retries while checking for long-running queries
  docs/mydumper_usage.rst
  mydumper.c
Labels: enhancement

#294 Check if directory exists
  myloader.c
Labels: enhancement

#287 Fix warnings in sphinx document generation
  docs/_build/conf.py.in
  docs/files.rst
Labels: Documentation

#233 Refactor logging and enable --logfile in myloader
  CMakeLists.txt
  binlog.c
  logging.c
  logging.h
  mydumper.c
  myloader.c
  set_verbose.c
  set_verbose.h
Labels: enhancement

#300 Simpler if condition for purge-mode
  myloader.c
Labels: bug

#153 Update README – include link to usage
  README.md
Labels: Documentation
