Repository mydumper/mydumper, pull requests merged in 2021-04, with the labels that each got.

#232 Adjust README.md to provide better CentOS 7 build instructions
  README.md
Labels: Documentation

#154 change to utf8mb4
  mydumper.c
  myloader.c
Labels: bug, enhancement, incomplete

#310 Correcting ubuntu/debian packages dependecies
  README.md
Labels: Documentation, bug

#302 Updating the download url
  README.md
Labels: Documentation

#312 Password obfuscation
  mydumper.c
  myloader.c
Labels: enhancement

#313 Adding homebrew build support
  cmake/modules/FindMySQL.cmake
Labels: bug, enhancement

#314 Adding IF NOT EXISTS to SHOW CREATE DATABASE
  mydumper.c
Labels: enhancement

#315 [refactoring] Adding function new_table_job
  mydumper.c
Labels: Refactoring

#319 fixing allowed in C99 mode error
  mydumper.c
Labels: bug

#320 fixing allowed in C99 mode error
  myloader.c
Labels: bug

#317 Fix issues when daemon is used on glist
  mydumper.c
Labels: bug
