Repository mydumper/mydumper, pull requests merged in 2021-11, with the labels that each got.

#475 Changing umask to restrinct access
  mydumper.c
Labels: Fix

#473 Adding IF NOT EXISTS to temporary create table for views
  mydumper.c
Labels: Fix

#476 Line tracking on error
  common.c
  common.h
  myloader.c
Labels: enhancement

#466 Removig backup dir created when stream is used
  common.c
  common.h
  mydumper.c
  myloader.c
Labels: enhancement

#489 Fixing no_delete when stream and filename on -F
  mydumper.c
  myloader.c
Labels: Fix

#472 Avoiding creating other databases when db is used
  myloader.c
Labels: Fix

#481 [ Refactoring ] Removing process_queue_less locking and binlog cleanup
  common.c
  common.h
  mydumper.c
  mydumper.h
  myloader.c
Labels: Refactoring

#461 Adding ignore generated fields parameter
  mydumper.c
Labels: enhancement

#307 Adding --load-data and others options to allow CSV output
  common.c
  common.h
  mydumper.c
  myloader.c
  myloader.h
Labels: enhancement

#459 Better logging implementation per thread
  mydumper.c
  myloader.c
  myloader.h
Labels: Refactoring

#479 [ Refactoring ] using just default config file, removing --config-file
  common.h
  mydumper.c
  myloader.c
Labels: Refactoring

#491 Doc didn't mention how to negate tables
  README.md
Labels: Documentation

#483 Changing backup dir permission to 750
  common.c
  mydumper.c
Labels: enhancement

#486 Adding remaining jobs in the dumping data comment
  mydumper.c
Labels: enhancement

#497 Fixing error on load_config_file after merge
  CMakeLists.txt
  common.c
  common.h
  mydumper.c
  myloader.c
Labels: Fix

#316 Add minimal CircleCI config
  .circleci/config.yml
Labels: enhancement

#482 Simulating mysqldump usage when database and tables is used
  mydumper.c
Labels: enhancement

#463 Post v0.11.3
  CMakeLists.txt
  README.md
Labels: Documentation

#453 Changing umask and fixing dump_directory
  mydumper.c
Labels: Fix
