Repository mydumper/mydumper, pull requests merged in 2021-10, with the labels that each got.

#415 Adding LC_ALL to allow multi-byte parameters
  mydumper.c
  myloader.c
Labels: Fix

#416 sync_before_add_index is not needed anymore
  myloader.c
Labels: Refactoring

#417 Warning for inconsistencies using multisource
  mydumper.c
Labels: Documentation

#412 docs: add brew build dependencies instruction
  README.md
Labels: Documentation

#419 Post v0.11.1
  CMakeLists.txt
  README.md
Labels: Documentation

#426 Fixing comment error log in restore_data_in_gstring_from_file
  myloader.c
Labels: Fix
