Repository mydumper/mydumper, pull requests merged in 2021-12, with the labels that each got.

#502 Adding swag button
  README.md
Labels: Documentation

#503 Fixing db file not being removed
  common.c
  myloader.c
Labels: Fix

#501 Fix filename line when myloader stream is used
  myloader.c
Labels: Fix

#95 Add Docker support
  Dockerfile
Labels: enhancement

#516 [Fix] Dynamic string length on variable
  myloader.c
Labels: Fix

#517 Removing message not needed
  myloader.c
Labels: Fix

#508 [ Stream ] Improving and fixing issues
  common.h
  mydumper.c
  myloader.c
Labels: Fix

#519 Adding set isolation level to repetable read to the main connection
  mydumper.c
Labels: Fix

#521 Split partition implementation
  mydumper.c
  mydumper.h
Labels: enhancement

#522 Pausing job creation when reach limit
  mydumper.c
Labels: Fix
