Repository mydumper/mydumper, pull requests merged in 2021-05, with the labels that each got.

#329 After release v0.10.5
  CMakeLists.txt
  README.md
Labels: Documentation

#118 specify number of snapshots
  CMakeLists.txt
  cmake/modules/FindGLIB2.cmake
  mydumper.c
Labels: enhancement

#227 Order by primary key
  mydumper.c
  mydumper.h
Labels: enhancement

#334 Option to automatically disable/enable REDO_LOG
  myloader.c
Labels: enhancement

#333 Moving detected_generated_fields as parameter in table_job
  mydumper.c
  mydumper.h
Labels: Refactoring, enhancement

#327 Adding wsrep_sync_wait support
  mydumper.c
Labels: enhancement

#286 Adding fast index creation functionality
  myloader.c
  myloader.h
Labels: enhancement

#349 Escaping quotes on detect_generated_fields as it caused seg fault
  mydumper.c
Labels: bug

#351 Fix as constraint was ignored
  myloader.c
Labels: Fix

#194 Added support for dumping checksums
  CMakeLists.txt
  common.c
  common.h
  mydumper.c
  mydumper.h
  myloader.c
Labels: enhancement
