Repository mydumper/mydumper, pull requests merged in 2022-04, with the labels that each got.

#633 Fix print time
  src/myloader_directory.c
Labels: Fix

#636 Adding critical message when DDL fails
  src/myloader_restore.c
Labels: Fix

#641 Allow compilation on Clang
  src/myloader_stream.c
Labels: Fix

#647 Fixing trigger absent when --no-schema is used
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
Labels: Fix

#619 Reengineering the DDL locks and connection sync
  CMakeLists.txt
  src/mydumper.c
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_database.c
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_stream.c
  src/mydumper_stream.h
  src/mydumper_working_thread.c
  src/mydumper_working_thread.h
Labels: Refactoring, Fix

#655 Adding better message when schema-create files are not provided
  src/myloader_process.c
Labels: Fix

#660 Adding PMM support for MyDumper
  CMakeLists.txt
  src/mydumper_jobs.c
  src/mydumper_pmm_thread.c
  src/mydumper_pmm_thread.h
  src/mydumper_start_dump.c
  src/mydumper_stream.c
  src/myloader.c
  src/myloader_pmm_thread.c
  src/myloader_pmm_thread.h
  src/myloader_stream.c
Labels: enhancement

#662 Fixing when DEFINER is absent and stream/intermediate sync when finish
  src/myloader_process.c
  src/myloader_restore.c
  src/myloader_stream.c
Labels: Fix

#661 Release 0.12.3-1
  CMakeLists.txt
Labels: Release

#614 Update README.md
  README.md
Labels: Documentation
