Repository mydumper/mydumper, pull requests merged in 2022-11, with the labels that each got.

#870 Char chunking refactored
  src/mydumper_chunks.c
  src/mydumper_chunks.h
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_write.c
Labels: Refactoring

#871 Removing column_type of schema checksum
  src/common.c
Labels: Fix

#874 Memory overwritten issue fixed
  src/mydumper_chunks.c
  src/mydumper_chunks.h
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
Labels: Fix

#875 Removing code causing segfault
  src/mydumper_chunks.c
  src/mydumper_common.c
  src/mydumper_jobs.c
  src/mydumper_working_thread.c
Labels: Fix

#876 Considering empty BLOB columns
  src/mydumper_chunks.c
  src/mydumper_write.c
Labels: Fix

#877 Making checksum queries compatible between versions
  src/common.c
Labels: Fix

#878 Getting query time and updating chunk size
  src/mydumper_working_thread.c
Labels: enhancement

#879 Fixing myloader as it is not respecting --innodb-optimize-keys
  src/myloader.h
  src/myloader_control_job.c
  src/myloader_process.c
  src/myloader_restore_job.c
Labels: Fix

#880 CHAR chunk refactored
  mydumper_testing_db_template.sql
  src/common.c
  src/common.h
  src/mydumper_chunks.c
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_working_thread.h
  src/mydumper_write.c
Labels: enhancement

#883 Fix on integer chunk to set right step
  src/mydumper_working_thread.c
  test_mydumper.sh
Labels: Fix

#891 Avoiding holes on integer pk
  src/mydumper_chunks.c
  src/mydumper_chunks.h
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
Labels: Fix

#892 Fix and adding single threaded on views
  src/mydumper_working_thread.c
  src/myloader_jobs_manager.c
Labels: Fix

#897 Bug on multithreaded exec
  src/mydumper_exec_command.c
Labels: Fix

#900 [ Bug ] Unexpected remove file entry and correct file rotation
  mydumper_testing_db_template.sql
  src/mydumper_jobs.c
  src/mydumper_stream.c
  src/mydumper_write.c
  src/myloader_restore.c
Labels: Fix

#901 STWRL removed from main connection
  src/mydumper_start_dump.c
Labels: Fix

#902 Adding table status and process data files even if table hasn't been …
  src/myloader.h
  src/myloader_control_job.c
  src/myloader_process.c
  src/myloader_restore_job.c
Labels: enhancement

#905 Changing key on dbt list
  src/myloader_common.c
  src/myloader_common.h
  src/myloader_process.c
Labels: Fix

#903 Refactoring escape when load data
  mydumper_testing_db_template.sql
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_jobs.c
  src/mydumper_write.c
  src/myloader.h
  src/myloader_common.c
  src/myloader_control_job.c
  src/myloader_intermediate_queue.c
  src/myloader_process.c
  src/myloader_restore_job.c
  src/myloader_stream.c
  test_mydumper.sh
Labels: Refactoring, Fix

#906 Creating job to determine chunk type
  src/mydumper_chunks.c
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
Labels: enhancement

#907 Setting chunk type after setting the chunk list
  src/mydumper_chunks.c
  src/mydumper_working_thread.c
Labels: Fix

#908 Typo myloader.c
  src/myloader.c
Labels: Fix

#909 [ Fix ] Index checksum review and index enqueuing fixed
  src/common.c
  src/mydumper_common.c
  src/myloader_control_job.c
  src/myloader_jobs_manager.c
  src/myloader_restore.c
  src/myloader_restore_job.c
  test_mydumper.sh
Labels: Fix

#913 Removing g_string_append_print due performance issue
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_write.c
Labels: Fix

#917 Add ASAN and TSAN sanitizers
  CMakeLists.txt
Labels: enhancement

#920 Rolling back add_link_options
  CMakeLists.txt
Labels: Fix

#923 Restoring the max threads per table functionality
  src/myloader_control_job.c
  src/myloader_restore_job.c
Labels: Fix
