Repository mydumper/mydumper, pull requests merged in 2023-01, with the labels that each got.

#957 Split the help
  src/common.c
  src/common.h
  src/common_options.h
  src/connection.c
  src/connection.h
  src/mydumper.c
  src/mydumper_chunks.c
  src/mydumper_chunks.h
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_daemon_thread.c
  src/mydumper_daemon_thread.h
  src/mydumper_exec_command.c
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_working_thread.h
  src/mydumper_write.c
  src/mydumper_write.h
  src/myloader.c
  src/myloader_restore.c
  src/regex.c
  src/regex.h
Labels: Documentation

#966 Docs: Updated compilation instructions for MacOS
  README.md
Labels: Documentation

#947 [BUG] Fix macOS build
  cmake/modules/FindMySQL.cmake
  src/mydumper_stream.c
  src/mydumper_write.c
  src/myloader.c
Labels: Fix

#971 Fixing bug on load_data
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_write.c
Labels: Fix

#972 Fixing character set issue
  src/common.c
  src/common.h
  src/common_options.h
  src/connection.c
  src/mydumper_chunks.c
  src/mydumper_common.c
  src/mydumper_jobs.c
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
  src/mydumper_write.c
  src/myloader.c
  src/myloader_jobs_manager.c
Labels: Fix

#974 Adding SET on LOAD DATA to convert json types
  src/mydumper_write.c
Labels: Fix

#976 Missing () when WHERE clause is used
  src/mydumper_working_thread.c
Labels: Fix

#981 Fixing spaces on LOAD DATA filename when compression is used
  src/myloader_control_job.c
  src/myloader_restore.c
  test_mydumper.sh
Labels: Fix

#982 Adding docker image builder
  docker/Dockerfile
  docker/bionic/Dockerfile
  docker/bionic/README.md
  docker/bullseye/Dockerfile
  docker/bullseye/README.md
  docker/buster/Dockerfile
  docker/buster/README.md
  docker/el7/Dockerfile
  docker/el7/README.md
  docker/el8/Dockerfile
  docker/el8/README.md
  docker/el9/Dockerfile
  docker/el9/README.md
  docker/focal/Dockerfile
  docker/focal/README.md
  docker/jammy/Dockerfile
  docker/jammy/README.md
Labels: enhancement, Refactoring

#929 Add `--debug` mode
  src/common_options.h
  src/logging.c
  src/mydumper.c
  src/myloader.c
  src/set_verbose.c
  src/set_verbose.h
Labels: enhancement

#983 Adding views-as-tables: views are considered non-innodb tables
  src/mydumper_working_thread.c
Labels: enhancement

#984 Adding global section
  src/common.c
  src/common.h
  src/common_options.h
  src/mydumper_chunks.c
  src/mydumper_jobs.c
  src/mydumper_start_dump.c
  src/mydumper_stream.c
  src/mydumper_working_thread.c
  src/mydumper_write.c
  src/myloader.c
  src/myloader_process.c
  src/myloader_restore_job.c
  src/myloader_stream.c
Labels: enhancement

#985 Removing EXITs to send the rollback for set global
  src/common.c
  src/common.h
  src/connection.c
  src/mydumper.c
  src/mydumper_daemon_thread.c
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
  src/mydumper_write.c
  src/myloader.c
  src/myloader_common.c
  src/myloader_common.h
  src/myloader_intermediate_queue.c
  src/myloader_jobs_manager.c
  src/myloader_process.c
  src/myloader_restore_job.c
  src/regex.c
  src/server_detect.c
  src/set_verbose.c
Labels: enhancement

#995 Adding /etc/mydumper.cnf as default file
  mydumper.cnf
  package/deb/files
  package/rpm/mydumper-zstd.spec
  package/rpm/mydumper.spec
  src/common.c
  src/common.h
  src/common_options.h
  src/mydumper.c
  src/mydumper_start_dump.c
  src/myloader.c
  src/myloader_jobs_manager.c
  src/server_detect.c
  src/server_detect.h
  test_mydumper.sh
Labels: enhancement

#996 Mutex for load data files on stream
  src/myloader.c
  src/myloader_intermediate_queue.c
  src/myloader_restore.c
  src/myloader_restore.h
Labels: enhancement

#997 Fixing sync issue
  src/myloader_restore.c
Labels: enhancement

#1001 Remove Drizzle support
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
  src/server_detect.c
  src/server_detect.h
Labels: Refactoring

#1002 Adding remaining jobs again
  src/mydumper_chunks.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_write.c
  src/mydumper_write.h
Labels: Refactoring

#1006 Change UNIQUE_CHECKS for all MariaDB versions
  mydumper.cnf
Labels: Fix

#1007 Adding file size control when streaming
  src/mydumper_stream.c
  src/myloader_stream.c
Labels: enhancement
