Repository mydumper/mydumper, pull requests merged in 2023-02, with the labels that each got.

#1014 Fixing glib2.0-0 dependency
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
  package/deb/control
  package/deb/control-zstd
Labels: Fix

#1011 Metadata file refactory
  src/common.c
  src/common.h
  src/mydumper_database.c
  src/mydumper_database.h
  src/mydumper_global.h
  src/mydumper_jobs.c
  src/mydumper_jobs.h
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/myloader.c
  src/myloader.h
  src/myloader_common.c
  src/myloader_common.h
  src/myloader_intermediate_queue.c
  src/myloader_process.c
  src/myloader_process.h
  src/myloader_restore.c
  src/myloader_restore_job.c
  test_mydumper.sh
Labels: Refactoring

#1030 Setting num_threads on dbt->max_threads when max_threads_per_table default value is higher
  src/myloader_process.c
Labels: Fix

#1035 Adding identifier-quote-character and delimiter with tests
  mydumper.cnf
  src/common.c
  src/common_options.c
  src/common_options.h
  src/connection.c
  src/connection.h
  src/mydumper_chunks.c
  src/mydumper_global.h
  src/mydumper_jobs.c
  src/mydumper_start_dump.c
  src/mydumper_write.c
  src/myloader.c
  src/myloader_global.h
  src/myloader_process.c
  test/mydumper.cnf
  test/mydumper_testing_db.sql
  test/mydumper_testing_db_template.sql
  test_mydumper.sh
Labels: enhancement

#1041 Detect that libMariaDB was built with SSL
  CMakeLists.txt
  cmake/modules/FindMySQL.cmake
Labels: enhancement

#1042 Add github action to automatically publish images to docker hub
  .github/workflows/docker.yml
Labels: enhancement

#1045 Reconnecting if execution failed
  src/connection.c
  src/mydumper_start_dump.c
  src/myloader_restore.c
Labels: enhancement

#1046 Adding message to let user know this is or isn't a consistent backup when --no-locks is used
  src/mydumper_global.h
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
Labels: enhancement

#1047 Add ability to build ARM docker images
  .github/workflows/docker.yml
Labels: enhancement

#1051 Leaving mysql default behavior when mydumper section is not found
  src/connection.c
Labels: Fix

#1052 Fixing issue
  src/myloader.c
Labels: Refactoring, Fix

#1053 Adding check when there is no non-innodb-table to lock
  src/mydumper_working_thread.c
Labels: Fix
