Repository mydumper/mydumper, pull requests merged in 2023-08, with the labels that each got.

#1237 Adding list of compression commands
  src/common.c
  src/common.h
  src/mydumper_chunks.h
  src/mydumper_global.h
  src/mydumper_jobs.c
  src/mydumper_working_thread.c
  src/myloader.c
  src/myloader_common.c
  src/myloader_common.h
  src/myloader_intermediate_queue.c
  src/myloader_process.c
Labels: Fix

#1239 Adding mkfifo checks
  src/mydumper_common.c
  src/myloader_restore.c
Labels: Fix

#1241 Removing schema when connection is established
  src/connection.c
  src/connection.h
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
  src/myloader.c
  src/myloader_restore.c
  src/myloader_worker_index.c
  src/myloader_worker_loader.c
  src/myloader_worker_post.c
  src/myloader_worker_schema.c
Labels: Fix

#1242 Implementing own waitpid
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_exec_command.c
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
Labels: Fix

#1243 Adding partition table filter per table in config file
  src/common.c
  src/common.h
  src/mydumper_chunks.c
  src/mydumper_chunks.h
  src/mydumper_common.c
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/regex.c
  src/regex.h
Labels: enhancement

#1246 Fixing file filter when source db is use
  src/myloader_common.c
Labels: Fix

#1251 Fix on row missing and refactoring
  src/common_options.c
  src/connection.c
  src/mydumper_arguments.c
  src/mydumper_chunks.c
  src/myloader_arguments.c
Labels: Refactoring, Fix

#1253 Missing check if mysql_fetch_row is NULL
  src/mydumper_jobs.c
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
  src/server_detect.c
Labels: Fix

#1260 Splitting testing functions
  CMakeLists.txt
  test_mydumper.sh
Labels: enhancement

#1259 Fixing new_minmax value issue when fixed chunk size
  src/mydumper_chunks.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
Labels: Fix

#1262 Fix table complete counting
  src/myloader_restore_job.c
Labels: Fix

#1272 Using semaphores to prevent excessive local file accumulation during output throttling.
  src/mydumper_start_dump.h
  src/mydumper_stream.c
Labels: enhancement

#1270 Fixing unused value error
  src/common.c
Labels: Fix

#1273 Adding check when getting master position
  src/mydumper_working_thread.c
Labels: Fix
