Repository mydumper/mydumper, pull requests merged in 2023-10, with the labels that each got.

#1312 [skip ci] fix
  cmake/modules/FindJeMalloc.cmake
Labels: enhancement

#1278 fix function: is_table_in_list
  src/common.c
  src/common.h
  src/mydumper_working_thread.c
  src/myloader_common.c
Labels: Fix

#1321 Fix on master after merge
  src/mydumper_global.h
  src/mydumper_jobs.c
  src/mydumper_pmm_thread.c
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
  src/myloader_intermediate_queue.c
  src/myloader_process.c
  src/myloader_stream.c
Labels: Fix

#1322 Sending shutdown to index worker when ctrl+c
  src/myloader_restore_job.c
Labels: Fix

#1323 Adding bookworm Dockerfile
  docker/bookworm/Dockerfile
  docker/bookworm/README.md
Labels: enhancement

#1324 Removing jemalloc as default
  CMakeLists.txt
Labels: Refactoring

#1177 Adding Debian 12 to CircleCI config
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: enhancement

#1327 Fixing locking issue
  src/mydumper_chunks.c
  src/mydumper_global.h
  src/mydumper_pmm_thread.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_write.c
Labels: Fix

#1329 Adding --no-schema and fixing checksums
  src/common_options.c
  src/mydumper_start_dump.c
  src/myloader.c
  src/myloader_arguments.c
  src/myloader_common.c
  src/myloader_global.h
  src/myloader_restore_job.c
Labels: bug, enhancement

#1330 Check NULL on release_global_lock_function missing
  src/mydumper_start_dump.c
Labels: Fix
