Repository mydumper/mydumper, pull requests merged in 2024-11, with the labels that each got.

#1656 Missing check on string len and cleanup bug
  src/mydumper_masquerade.c
Labels: Fix

#1658 Add row delimiter
  src/mydumper_integer_chunks.c
  src/mydumper_integer_chunks.h
  src/mydumper_write.c
Labels: Enhancement, Refactoring, Fix

#1659 Moving debian/ubuntu packages to the right dir
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Enhancement, Fix

#1660 Moving debian/ubuntu packages to the right dir
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Fix

#1661 Moving debian/ubuntu packages to the right dir
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Fix

#1665 Moving Dockerfile to right folder
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
  .github/workflows/docker-image-with-parameter.yml
  .github/workflows/docker-image.yml
  .github/workflows/docker.yml
  Dockerfile
  docker/Dockerfile
Labels: Enhancement

#1666 Test for table with comment has VIEW
  mydumper_testing_db_template.sql
  test/mydumper_testing_db_template.sql
Labels: Fix

#1664 Engine should be NULL to be consider a view, not just comment
  src/mydumper_working_thread.c
Labels: Fix

#1668 Fixing MIN_CHUNK_STEP_SIZE default value issue
  src/mydumper_chunks.h
Labels: Fix

#1669 add periodic github check to see if nixpkgs updated successfully
  .github/workflows/check_nixpkgs_update.yml
Labels: Enhancement

#1675 Setting right max limit
  src/mydumper_masquerade.c
Labels: Fix

#1677 Signal thread is not created on demonized executions
  src/mydumper_start_dump.c
Labels: Fix

#1683 Adding parameter to functions
  src/mydumper/mydumper_chunks.c
  src/mydumper/mydumper_common.c
  src/mydumper/mydumper_create_jobs.c
  src/mydumper/mydumper_jobs.c
  src/myloader/myloader_common.c
  src/myloader/myloader_restore_job.h
  src/myloader/myloader_stream.c
Labels: Refactoring

#1685 Changing critical to error to see the file that is failing
  src/myloader/myloader_restore.c
Labels: Fix
