Repository mydumper/mydumper, pull requests merged in 2024-07, with the labels that each got.

#1548 Fixing start replica issues
  src/mydumper_start_dump.c
Labels: Fix

#1546 Adding EL repo
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: enhancement

#1549 [ Repo ] Adding final changes to the initial yum and apt repo
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: enhancement

#1550 Adding repo final changes
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: enhancement, Fix

#1552 [ Repo ] Fix on rpmmacros
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Fix

#1553 Creating testing repo
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: enhancement

#1555 Moving build from percona57 to percona80 on el8
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: enhancement

#1520 Adding progress report and better info
  src/mydumper_chunks.c
  src/mydumper_integer_chunks.c
  src/mydumper_working_thread.c
  src/mydumper_write.c
  src/myloader_restore_job.c
Labels: enhancement

#1557 Fix building on musl libc
  src/mydumper_file_handler.c
  src/mydumper_stream.c
Labels: Fix

#1558 fix build error
  src/mydumper_stream.c
Labels: Fix

#1561 Changing --rows behavior
  src/mydumper.c
  src/mydumper_arguments.c
  src/mydumper_char_chunks.c
  src/mydumper_chunks.c
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_global.h
  src/mydumper_integer_chunks.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_write.c
Labels: enhancement

#1562 Adding html folder for web access
  .gitignore
  docs/html/authors.html
  docs/html/compiling.html
  docs/html/examples.html
  docs/html/files.html
  docs/html/genindex.html
  docs/html/index.html
  docs/html/mydumper_usage.html
  docs/html/myloader_usage.html
  docs/html/search.html
Labels: Documentation

#1564 Adding static files
  .gitignore
  docs/html/_static/basic.css
  docs/html/_static/classic.css
  docs/html/_static/default.css
  docs/html/_static/doctools.js
  docs/html/_static/documentation_options.js
  docs/html/_static/file.png
  docs/html/_static/jquery.js
  docs/html/_static/language_data.js
  docs/html/_static/minus.png
  docs/html/_static/plus.png
  docs/html/_static/pygments.css
  docs/html/_static/searchtools.js
  docs/html/_static/sidebar.js
  docs/html/_static/underscore.js
Labels: Documentation

#1565 Initial/minor documentation improvement before creating submodule
  docs/authors.rst
  docs/files.rst
  docs/index.rst
  docs/mydumper_usage.rst
  docs/myloader_usage.rst
Labels: Documentation

#1568 Fixing columns name on show replica status
  src/mydumper_start_dump.c
Labels: Fix

#1571 Adding --source-data on mydumper to set the confing to apply replication on myloader
  src/mydumper_arguments.c
  src/mydumper_global.h
  src/mydumper_start_dump.c
  src/mydumper_working_thread.c
  src/myloader_common.c
  src/myloader_process.c
Labels: enhancement

#1573 Adding object_to_export on myloader
  src/common.c
  src/common.h
  src/mydumper_masquerade.c
  src/mydumper_masquerade.h
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/myloader.c
  src/myloader.h
  src/myloader_common.c
  src/myloader_common.h
  src/myloader_global.h
  src/myloader_process.c
  src/myloader_restore_job.c
Labels: enhancement

#1574 Implemeting FORMAT MySQLDump for clickhouse
  src/mydumper.c
  src/mydumper_arguments.c
  src/mydumper_arguments.h
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_global.h
  src/mydumper_jobs.c
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_write.c
  src/myloader_restore_job.c
  src/server_detect.c
  src/server_detect.h
Labels: enhancement

#1576 Adding GTID replication option and cloud based solution (AWS for now)
  src/mydumper_working_thread.c
  src/myloader_arguments.c
  src/myloader_arguments.h
  src/myloader_common.c
  src/myloader_global.h
Labels: enhancement

#1577 AFTER_IMPORT_PER_TABLE is the new default and SKIP was added on --innodb-optimize-keys
  src/myloader.c
  src/myloader_arguments.c
  src/myloader_arguments.h
Labels: enhancement

#1578 Adding --ignore-set on myloader
  src/myloader_arguments.c
  src/myloader_common.c
  src/myloader_common.h
  src/myloader_global.h
  src/myloader_restore.c
Labels: enhancement
