Repository mydumper/mydumper, pull requests merged in 2024-03, with the labels that each got.

#1415 Refactoring file handling
  .gitignore
  CMakeLists.txt
  src/common.c
  src/common.h
  src/common_options.c
  src/mydumper.c
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_daemon_thread.c
  src/mydumper_file_handler.c
  src/mydumper_file_handler.h
  src/mydumper_global.h
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_write.c
  src/myloader_global.h
  src/myloader_restore.c
Labels: Refactoring

#1417 When connecting to MySQL, if client group exists in the x.cnf, ignore others
  src/common.c
Labels: enhancement

#1419 fix split partitions
  src/mydumper_chunks.c
Labels: Fix

#1425 Fix mixes up triggers from different tables
  src/mydumper_jobs.c
Labels: Fix

#1429 Adding --include-header to add head when --load-data/--csv is used
  src/mydumper_arguments.c
  src/mydumper_common.c
  src/mydumper_common.h
  src/mydumper_global.h
  src/mydumper_start_dump.c
  src/mydumper_start_dump.h
  src/mydumper_working_thread.c
  src/mydumper_write.c
  src/mydumper_write.h
Labels: enhancement

#1433 Adding --skip-ddl-lock
  src/mydumper_arguments.c
  src/mydumper_global.h
  src/mydumper_start_dump.c
Labels: enhancement

#1442 Setting --use-defer as option and removing --skip-defer
  src/common.c
  src/mydumper.c
  src/mydumper_arguments.c
  src/mydumper_chunks.c
  src/mydumper_global.h
Labels: Refactoring

#1447 Support multiple --regex
  src/mydumper_database.c
  src/mydumper_working_thread.c
  src/regex.c
  src/regex.h
Labels: enhancement
