Repository mydumper/mydumper, pull requests merged in 2024-08, with the labels that each got.

#1579 Fixing some missing AWS commands
  src/mydumper_working_thread.c
  src/myloader_common.c
Labels: enhancement, Fix

#1581 Fixing setting NULL to the connection before completing the statement
  src/mydumper_integer_chunks.c
  src/myloader_restore.c
Labels: Fix

#1583 ->len on the GString is not updated
  src/mydumper_write.c
Labels: Fix

#1587 Comment source log file and pos when auto position is selected
  src/mydumper_working_thread.c
Labels: Fix

#1591 Unifying reconnection in a single place
  src/myloader_restore.c
Labels: Fix

#1593 Fixing begin-commit transaction during import
  src/myloader_restore.c
Labels: Fix

#1592 Update README.md
  README.md
Labels: Documentation
