Repository mydumper/mydumper, pull requests merged in 2025-04, with the labels that each got.

#1825 Refactoring multicolumn
  src/mydumper/mydumper_chunks.c
  src/mydumper/mydumper_chunks.h
  src/mydumper/mydumper_create_jobs.c
  src/mydumper/mydumper_integer_chunks.c
  src/mydumper/mydumper_integer_chunks.h
  src/mydumper/mydumper_start_dump.h
  src/mydumper/mydumper_write.c
Labels: Enhancement, Refactoring, Fix

#1826 Fixing m_store_result_row/m_store_result_single_row return values
  src/common.c
  src/mydumper/mydumper_chunks.c
  src/mydumper/mydumper_integer_chunks.c
  src/mydumper/mydumper_jobs.c
  src/mydumper/mydumper_start_dump.c
  src/server_detect.c
Labels: Fix

#1828 Removing pcre.h
  src/common.h
  src/connection.c
  src/logging.c
  src/mydumper/mydumper_common.c
  src/server_detect.c
  src/set_verbose.c
Labels: Refactoring, Fix

#1832 Adding -e back
  src/myloader/myloader.c
  src/myloader/myloader_arguments.c
  src/myloader/myloader_global.h
Labels: Refactoring

#1833 Moving replica status write to worker
  src/mydumper/mydumper_global.h
  src/mydumper/mydumper_start_dump.c
  src/mydumper/mydumper_working_thread.c
Labels: Fix

#1835 Fixing repo
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Fix

#1838 Fixing circleci config
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Fix

#1842 Adding build with default mysql libraries on Noble
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Enhancement

#1847 docs: fix docker build command
  README.md
Labels: Documentation

#1850 Fixing numbers in the file
  src/mydumper/mydumper_chunks.c
  src/mydumper/mydumper_create_jobs.c
  src/mydumper/mydumper_create_jobs.h
  src/mydumper/mydumper_integer_chunks.c
  src/mydumper/mydumper_partition_chunks.c
  src/mydumper/mydumper_start_dump.h
  src/mydumper/mydumper_working_thread.c
  src/mydumper/mydumper_write.c
  src/mydumper/mydumper_write.h
Labels: Fix

#1854 Adding message when --innodb-optimize-keys is used
  src/myloader/myloader_arguments.c
Labels: Enhancement, Documentation, Fix

#1852 Removing memory leak
  src/mydumper/mydumper_write.c
Labels: Fix

#1853 Splitting write_replica_info into 2 processes
  src/mydumper/mydumper_global.h
  src/mydumper/mydumper_start_dump.c
  src/mydumper/mydumper_working_thread.c
Labels: Enhancement, Fix

#1855 Fail if --exec-per-thread is used without --exec-per-thread-extension
  src/common.h
  src/mydumper/mydumper_jobs.c
  src/mydumper/mydumper_working_thread.c
  src/mydumper/mydumper_working_thread.h
Labels: Fix

#1856 Adding --merge
  src/mydumper/mydumper.c
  src/mydumper/mydumper_arguments.c
  src/mydumper/mydumper_global.h
  src/mydumper/mydumper_start_dump.c
  src/mydumper/mydumper_working_thread.c
  src/myloader/myloader_common.c
Labels: Enhancement

#1858 Fixing bugs on mysqldump formats
  src/myloader/myloader_stream.c
Labels: Enhancement, Fix
