Repository mydumper/mydumper, pull requests merged in 2025-01, with the labels that each got.

#1714 Adding mysqldump support and constant for masquerade
  src/common.c
  src/mydumper/mydumper_masquerade.c
  src/myloader/myloader.c
  src/myloader/myloader.h
  src/myloader/myloader_arguments.c
  src/myloader/myloader_global.h
  src/myloader/myloader_restore.c
  src/myloader/myloader_restore.h
  src/myloader/myloader_stream.c
Labels: Enhancement

#1717 Check if collation is missing
  src/mydumper/mydumper_masquerade.c
  src/mydumper/mydumper_working_thread.c
Labels: Fix

#1718 Fixing uuid bug on masquerade
  src/mydumper/mydumper_masquerade.c
Labels: Fix

#1727 Fixing possible overflow on integer chunks
  src/mydumper/mydumper_integer_chunks.c
Labels: Fix

#1729 add note about versioning to readme
  README.md
Labels: Documentation

#1730 Adding manual to the packages
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
  package/deb/files
  package/rpm/mydumper.spec
Labels: Enhancement, Documentation

#1733 Fixing bug when random_string is receiving null string
  src/mydumper/mydumper_masquerade.c
Labels: Fix

#1735 Adding START SLAVE UNTIL option
  src/myloader/myloader.c
  src/myloader/myloader.h
  src/myloader/myloader_common.c
  src/myloader/myloader_common.h
  src/myloader/myloader_global.h
  src/myloader/myloader_process.c
Labels: Enhancement

#1737 Adding % completed per table to INSERT statement on myloader
  src/myloader/myloader.h
  src/myloader/myloader_process.c
  src/myloader/myloader_restore.c
  src/myloader/myloader_restore.h
Labels: Enhancement

#1739 Adding -e depreation message
  mydumper.cnf
  src/myloader/myloader_arguments.c
Labels: Enhancement

#1747 Checks added when NULL is received in masquerade functions
  src/mydumper/mydumper_masquerade.c
Labels: Fix

#1744 Adding --rows-hard option for integer chunks
  src/mydumper/mydumper_arguments.c
  src/mydumper/mydumper_chunks.c
  src/mydumper/mydumper_common.c
  src/mydumper/mydumper_common.h
  src/mydumper/mydumper_integer_chunks.c
  src/mydumper/mydumper_integer_chunks.h
  src/mydumper/mydumper_working_thread.c
Labels: Fix

#1759 Memory not been released
  src/mydumper/mydumper_write.c
Labels: Fix

#1756 Printing error only if errors are found
  src/myloader/myloader.c
Labels: Fix
