Repository mydumper/mydumper, pull requests merged in 2025-02, with the labels that each got.

#1764 Decrease Docker image size
  docker/Dockerfile
Labels: Enhancement

#1766 Adding check if loop is not NULL
  src/mydumper/mydumper_start_dump.c
  src/myloader/myloader_restore_job.c
Labels: Fix

#1753 Removing locking options and adding --sync-thread-lock-mode to replace it
  src/mydumper/mydumper.c
  src/mydumper/mydumper_arguments.c
  src/mydumper/mydumper_global.h
  src/mydumper/mydumper_integer_chunks.c
  src/mydumper/mydumper_start_dump.c
  src/mydumper/mydumper_start_dump.h
  src/mydumper/mydumper_working_thread.c
  test_mydumper.sh
Labels: Enhancement

#1770 Fixing --exec
  src/mydumper/mydumper_exec_command.c
  src/mydumper/mydumper_exec_command.h
  src/mydumper/mydumper_file_handler.c
  src/mydumper/mydumper_file_handler.h
  src/mydumper/mydumper_global.h
  src/mydumper/mydumper_start_dump.c
  src/mydumper/mydumper_start_dump.h
  src/mydumper/mydumper_stream.c
Labels: Fix

#1772 Refactoring thread new calls
  src/common.c
  src/common.h
  src/mydumper/mydumper_chunks.c
  src/mydumper/mydumper_daemon_thread.c
  src/mydumper/mydumper_exec_command.c
  src/mydumper/mydumper_file_handler.c
  src/mydumper/mydumper_pmm_thread.c
  src/mydumper/mydumper_start_dump.c
  src/mydumper/mydumper_stream.c
  src/mydumper/mydumper_working_thread.c
  src/myloader/myloader.c
  src/myloader/myloader_control_job.c
  src/myloader/myloader_intermediate_queue.c
  src/myloader/myloader_restore.c
  src/myloader/myloader_stream.c
  src/myloader/myloader_worker_index.c
  src/myloader/myloader_worker_loader.c
  src/myloader/myloader_worker_post.c
  src/myloader/myloader_worker_schema.c
Labels: Enhancement, Refactoring, Fix

#1775 Moving to PCRE2 and adding regex to masquerade
  CMakeLists.txt
  cmake/modules/FindPCRE2.cmake
  src/common.c
  src/common.h
  src/mydumper/mydumper_masquerade.c
  src/mydumper/mydumper_masquerade.h
  src/mydumper/mydumper_start_dump.h
  src/regex.c
  src/regex.h
Labels: Enhancement, Refactoring, Feature Request

#1776 Fixing compilation issue when MariaDB libraries were use on Debian in ARM
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
  CMakeLists.txt
  src/connection.c
  src/mydumper/mydumper.c
  src/myloader/myloader.c
Labels: Enhancement, Fix

#1777 Fixing repo related issues
  .circleci/circleci_config_builder.sh
  .circleci/config.yml
Labels: Fix
